import { requireAdmin } from "@/lib/auth";
import { query } from "@/lib/db";
import { setUserStatusAction,setLinkStatusAction,deleteAnyLinkAction,rescanLinkRiskAction } from "@/actions/admin";
import { Message } from "@/components/Message";
import { ConfirmSubmit } from "@/components/ConfirmSubmit";
import Link from "next/link";
import { Logo } from "@/components/Logo";
import { logoutAction } from "@/actions/auth";

export const dynamic = "force-dynamic";

function riskBadge(state:string){
  if(state==="SAFE")return "badge-active";
  if(state==="BLOCKED")return "badge-deleted";
  return "badge-locked";
}

export default async function AdminPage({searchParams}:{searchParams:Promise<{error?:string;success?:string}>}){
  const admin=await requireAdmin(); const messages=await searchParams;
  const [stats,users,links,reports,audit]=await Promise.all([
    query<{users:string;links:string;visits:string;suspicious:string;blocked:string;reports:string}>(`SELECT (SELECT COUNT(*) FROM users)::text users,(SELECT COUNT(*) FROM share_links WHERE status<>'DELETED')::text links,(SELECT COUNT(*) FROM visits)::text visits,(SELECT COUNT(*) FROM share_links WHERE status<>'DELETED' AND risk_state='SUSPICIOUS')::text suspicious,(SELECT COUNT(*) FROM share_links WHERE status<>'DELETED' AND risk_state='BLOCKED')::text blocked,(SELECT COUNT(*) FROM link_reports WHERE created_at>NOW()-INTERVAL '7 days')::text reports`),
    query<{id:string;username:string;email:string|null;role:string;status:string;created_at:Date}>(`SELECT id,username,email,role,status,created_at FROM users ORDER BY created_at DESC LIMIT 50`),
    query<{id:string;name:string;slug:string;status:string;visit_count:string;username:string;risk_state:string;risk_score:number;risk_checked_at:Date|null}>(`SELECT l.id,l.name,l.slug,l.status,l.visit_count::text,u.username,l.risk_state,l.risk_score,l.risk_checked_at FROM share_links l JOIN users u ON u.id=l.user_id WHERE l.status<>'DELETED' ORDER BY CASE l.risk_state WHEN 'BLOCKED' THEN 0 WHEN 'SUSPICIOUS' THEN 1 WHEN 'UNKNOWN' THEN 2 ELSE 3 END,l.created_at DESC LIMIT 50`),
    query<{id:string;slug:string;reason:string;details:string|null;auto_state:string|null;auto_score:number|null;created_at:Date}>(`SELECT r.id::text,l.slug,r.reason,r.details,r.auto_state,r.auto_score,r.created_at FROM link_reports r JOIN share_links l ON l.id=r.link_id ORDER BY r.created_at DESC LIMIT 30`),
    query<{id:string;action:string;target_type:string;target_id:string;created_at:Date;username:string}>(`SELECT a.id::text,a.action,a.target_type,a.target_id,a.created_at,u.username FROM audit_logs a JOIN users u ON u.id=a.admin_user_id ORDER BY a.created_at DESC LIMIT 20`)
  ]);
  const s=stats.rows[0]??{users:"0",links:"0",visits:"0",suspicious:"0",blocked:"0",reports:"0"};
  return <div className="admin-shell"><header className="admin-header"><Logo href="/admin"/><nav><Link href="/dashboard">User Dashboard</Link><span className="badge badge-active">ADMIN</span><form action={logoutAction}><button className="btn btn-ghost btn-sm">Đăng xuất</button></form></nav></header><main className="admin-content"><div className="admin-welcome">Đăng nhập với <strong>{admin.display_name||admin.username}</strong></div><div className="page-heading"><div><span className="eyebrow">ADMIN PANEL</span><h1>Quản trị SHARE LINK</h1><p>Risk Engine tự quét link mới, quét lại theo thời gian và khi có báo cáo.</p></div></div><Message error={messages.error} success={messages.success}/><div className="stats-grid"><Stat label="Tổng Share Link" value={s.links}/><Stat label="Tổng lượt truy cập" value={Number(s.visits).toLocaleString("vi-VN")}/><Stat label="Link cần chú ý" value={s.suspicious}/><Stat label="Auto blocked" value={s.blocked}/></div>
    <section className="panel"><div className="panel-head"><div><h2>Risk Queue</h2><p>Link nguy hiểm được tự chặn; link đáng ngờ cần theo dõi hoặc Admin quét lại.</p></div><small>{s.reports} báo cáo trong 7 ngày</small></div><div className="table-wrap"><table><thead><tr><th>Link</th><th>Chủ sở hữu</th><th>Risk</th><th>Visit</th><th>Trạng thái</th><th>Quản lý</th></tr></thead><tbody>{links.rows.map(l=><tr key={l.id}><td><strong>{l.name}</strong><small className="cell-sub">/s/{l.slug}</small></td><td>@{l.username}</td><td><span className={`badge ${riskBadge(l.risk_state)}`}>{l.risk_state}</span><small className="cell-sub">score {Number(l.risk_score)||0}/100{l.risk_checked_at?` · ${new Date(l.risk_checked_at).toLocaleString("vi-VN")}`:" · chưa quét"}</small></td><td>{Number(l.visit_count).toLocaleString("vi-VN")}</td><td><span className={`badge badge-${l.status.toLowerCase()}`}>{l.status}</span></td><td><div className="actions"><form action={rescanLinkRiskAction}><input type="hidden" name="linkId" value={l.id}/><button className="btn btn-ghost btn-sm">Quét lại</button></form><form action={setLinkStatusAction}><input type="hidden" name="linkId" value={l.id}/><input type="hidden" name="status" value={l.status==='ACTIVE'?'LOCKED':'ACTIVE'}/><button className="btn btn-secondary btn-sm">{l.status==='ACTIVE'?'Khóa':'Mở khóa'}</button></form><form action={deleteAnyLinkAction}><input type="hidden" name="linkId" value={l.id}/><ConfirmSubmit message="Xóa Share Link này khỏi hệ thống?">Xóa</ConfirmSubmit></form></div></td></tr>)}</tbody></table></div></section>
    <section className="panel"><div className="panel-head"><div><h2>Báo cáo gần nhất</h2><p>Report chỉ là tín hiệu; gửi report sẽ kích hoạt quét tự động chứ không tự khóa mù quáng.</p></div></div>{reports.rowCount?<div className="audit-list">{reports.rows.map(r=><div key={r.id}><span>{new Date(r.created_at).toLocaleString("vi-VN")}</span><strong>/s/{r.slug} · {r.reason}</strong><small>Auto: {r.auto_state||"UNKNOWN"} · score {r.auto_score??0}{r.details?` · ${r.details}`:""}</small></div>)}</div>:<div className="empty-state">Chưa có báo cáo vi phạm.</div>}</section>
    <section className="panel"><div className="panel-head"><div><h2>Người dùng</h2><p>50 tài khoản mới nhất.</p></div></div><div className="table-wrap"><table><thead><tr><th>User</th><th>Vai trò</th><th>Trạng thái</th><th>Ngày tạo</th><th>Quản lý</th></tr></thead><tbody>{users.rows.map(u=><tr key={u.id}><td><strong>{u.username}</strong><small className="cell-sub">{u.email||"Không có email"}</small></td><td>{u.role}</td><td><span className={`badge badge-${u.status.toLowerCase()}`}>{u.status}</span></td><td>{new Date(u.created_at).toLocaleDateString("vi-VN")}</td><td><form action={setUserStatusAction}><input type="hidden" name="userId" value={u.id}/><input type="hidden" name="status" value={u.status==='ACTIVE'?'LOCKED':'ACTIVE'}/><button className={`btn btn-sm ${u.status==='ACTIVE'?'btn-danger':'btn-secondary'}`}>{u.status==='ACTIVE'?'Khóa':'Mở khóa'}</button></form></td></tr>)}</tbody></table></div></section>
    <section className="panel"><div className="panel-head"><div><h2>Audit Log</h2><p>Lịch sử thao tác quản trị gần nhất.</p></div></div>{audit.rowCount?<div className="audit-list">{audit.rows.map(a=><div key={a.id}><span>{new Date(a.created_at).toLocaleString("vi-VN")}</span><strong>{a.action}</strong><small>{a.username} · {a.target_type} · {a.target_id}</small></div>)}</div>:<div className="empty-state">Chưa có thao tác Admin.</div>}</section>
  </main></div>;
}
function Stat({label,value}:{label:string;value:string}){return <div className="stat-card"><span>{label}</span><strong>{value}</strong><small>toàn hệ thống</small></div>}
